
<form action="" method="post">
    <label for="name">Name :
        <input type="text" class="name" name="name">
    </label><br>
    <label for="category">Category name :
        <input type="text" class="category" name="category">
    </label><br>
    <label for="price">Price :
        <input type="text" class="price" name="price">
    </label><br>
    <label for="stock">Stock :
        <input type="text" class="stock" name="stock">
    </label><br>

    <div id="additionalField">
        <input type="button" value="Additional Fields" id="addFieldsButton" onclick="">

        <div id="addedFields">
            <br>

        </div>
    </div>

    <br><br>

    <div id="additionalVariations">
        <input type="button" value="Add Variations" id="addVariations" onclick="">
        <!-- <br><br>&nbsp;&nbsp;
        <input type="button" value="Add Attributes" id="addAttributesButton" onclick=""> -->

        <div id="addedVariations">
            <br>
        </div>
    </div>
</form>
