<?php


echo '<br>';

echo $this->tag->linkTo(
    ['store/products',
    'Products',
    'class'=>"btn btn-lg btn-success"]
);

echo '&nbsp;';

echo '&nbsp;';

echo $this->tag->linkTo(
    ['store/addProduct',
    'Add Product',
    'class'=>"btn btn-lg btn-success"]
);

echo '&nbsp;';

echo '&nbsp;';

echo $this->tag->linkTo(
    ['store/orders',
    'Orders',
    'class'=>"btn btn-lg btn-success"]
);

echo '&nbsp;';

echo '&nbsp;';

echo $this->tag->linkTo(
    ['store/addOrder',
    'Add Order',
    'class'=>"btn btn-lg btn-success"]
);

echo '<br>';
echo '<br>';
echo '<br>'; 
?>


<form action="addProduct" method="post">
    <label for="name">Name :
        <input type="text" class="name" name="name">
    </label><br>
    <label for="category">Category name :
        <input type="text" class="category" name="category">
    </label><br>
    <label for="price">Price :
        <input type="text" class="price" name="price">
    </label><br>
    <label for="stock">Stock :
        <input type="text" class="stock" name="stock">
    </label><br>

    <div id="additionalField">
        <input type="button" value="Additional Fields" id="addFieldsButton">

        <div id="addedFields">
            <br>

        </div>
    </div>

    <br><br>

    <div id="additionalVariations">
        <input type="button" value="Add Variations" id="addVariations">

        <div id="addedVariations">
            <br>
        </div>
    </div>

    <button type="submit">Add Product</button>
</form>
