<?php


echo '<br>';

echo $this->tag->linkTo(
    ['store/products',
    'Products',
    'class'=>"btn btn-lg btn-success"]
);

echo '<br>';

echo '<br>';

echo $this->tag->linkTo(
    ['store/addProduct',
    'Add Product',
    'class'=>"btn btn-lg btn-success"]
);

echo '<br>';

echo '<br>';

echo $this->tag->linkTo(
    ['store/orders',
    'Orders',
    'class'=>"btn btn-lg btn-success"]
);

echo '<br>';

echo '<br>';

echo $this->tag->linkTo(
    ['store/addOrder',
    'Add Order',
    'class'=>"btn btn-lg btn-success"]
);

echo '<br>';
