
<ul class="nav nav-pills nav-fill">
    <li class="nav-item">
        <a class="nav-link btn-outline-success" href="detailWeather?name=<?= $name ?>"><b>Current weather</b></a>
    </li>
    &nbsp;
    <li class="nav-item">
        <a class="nav-link btn-outline-primary" href="forecast?name=<?= $name ?>">Forecast</a>
    </li>
    &nbsp;

    <li class="nav-item">
        <a class="nav-link btn-info active" aria-current="page" href="#">History</a>
    </li>
    &nbsp;

    <li class="nav-item">
        <a class="nav-link btn-outline-light text-grey" href="timeZone?name=<?= $name ?>">Time Zone</a>
    </li>
    &nbsp;

    <li class="nav-item">
        <a class="nav-link btn-outline-info" href="sports?name=<?= $name ?>">Sports</a>
    </li>
    &nbsp;

    <li class="nav-item">
        <a class="nav-link btn-outline-info" href="astronomy?name=<?= $name ?>">Astronomy</a>
    </li>
    &nbsp;

    <li class="nav-item">
        <a class="nav-link btn-outline-danger" href="weatherAlerts?name=<?= $name ?>">Weather Alerts</a>
    </li>
    &nbsp;

    <li class="nav-item">
        <a class="nav-link btn-outline-warning" href="airQuality?name=<?= $name ?>">Air Quality</a>
    </li>
    &nbsp;

</ul>

<?php 



?>
