<ul class="nav nav-pills nav-fill">
    <li class="nav-item">
        <a class="nav-link btn-success active" aria-current="page" href="#"><b>Current weather</b></a>
    </li>
    &nbsp;
    <li class="nav-item">
        <a class="nav-link btn btn-outline-primary" href="forecast?name=<?= $response['location']['name'] ?>">Forecast</a>
    </li>
    &nbsp;

    <li class="nav-item">
        <a class="nav-link btn btn-outline-info" href="history?name=<?= $response['location']['name'] ?>">History</a>
    </li>
    &nbsp;

    <li class="nav-item">
        <a class="nav-link btn btn-outline-dark" href="timeZone?name=<?= $response['location']['name'] ?>">Time Zone</a>
    </li>
    &nbsp;

    <li class="nav-item">
        <a class="nav-link btn btn-outline-info" href="sports?name=<?= $response['location']['name'] ?>">Sports</a>
    </li>
    &nbsp;

    <li class="nav-item">
        <a class="nav-link btn btn-outline-info" href="astronomy?name=<?= $response['location']['name'] ?>">Astronomy</a>
    </li>
    &nbsp;

    <li class="nav-item">
        <a class="nav-link btn btn-outline-danger" href="weatherAlerts?name=<?= $response['location']['name'] ?>">Weather Alerts</a>
    </li>
    &nbsp;

    <li class="nav-item">
        <a class="nav-link btn btn-outline-warning" href="airQuality?name=<?= $response['location']['name'] ?>">Air Quality</a>
    </li>
    &nbsp;

</ul>

<?php

// echo "<pre>";
// // die;
// print_r($response);
// // die;
?>

<!-- < ?= $response ?> -->

<section class="vh-100" style="background-color: #ababab;">
    <div class="container py-5 h-100">

        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col-md-8 col-lg-6 col-xl-4">

                <div class="card" style="color: #4B515D; border-radius: 35px;">
                    <div class="card-body p-4">

                        <div class="d-flex">
                            <h6 class="flex-grow-1"><?= $response['location']['name'] ?></h6>
                            <h6><?= $response['location']['localtime'] ?></h6>
                        </div>

                        <div class="d-flex flex-column text-center mt-5 mb-4">
                            <h6 class="display-4 mb-0 font-weight-bold" style="color: #1C2331;"> <?= $response['current']['temp_c'] ?>°C / <?= $response['current']['temp_f'] ?>°F  </h6>
                            <span class="medium" style="color: #868B94"><?= $response['current']['condition']['text'] ?></span>
                        </div>
                        
                        <div class="d-flex align-items-center">
                            <div class="flex-grow-1" style="font-size: 1rem;">
                                <div><i class="fas fa-wind fa-fw" style="color: #868B94;"></i> <span class="ms-1">Wind Speed : <?= $response['current']['wind_kph'] ?> km/h & <?= $response['current']['wind_mph'] ?> m/h </span></div>
                                <div><i class="fas fa-tint fa-fw" style="color: #868B94;"></i> <span class="ms-1">Humidity : <?= $response['current']['humidity'] ?> %</span></div>
                                <div><i class="fa-solid fa-clouds" style="color: #868B94;"></i> <span class="ms-1">Clouds : <?= $response['current']['cloud'] ?> %</span></div>
                                <div><i class="fas fa-sun fa-fw" style="color: #868B94;"></i> <span class="ms-1">Wind Direction : <?= $response['current']['wind_dir'] ?> </span></div>
                                <div><i class="fas fa-sun fa-fw" style="color: #868B94;"></i> <span class="ms-1">UV : <?= $response['current']['uv'] ?> %</span></div>
                            </div>
                            <div>
                                <img src="<?= $response['current']['condition']['icon'] ?>" width="100px">
                            </div>
                        </div>

                    </div>
                    <span class="small text-center" style="color: #868B94">Last Updated : <?= $response['current']['last_updated'] ?></span>
                </div>

            </div>

        </div>

    </div>
</section>