<ul class="nav nav-pills nav-fill">
    <li class="nav-item">
        <a class="nav-link btn-outline-success" href="detailWeather?name=<?= $response['location']['name'] ?>"><b>Current weather</b></a>
    </li>
    &nbsp;
    <li class="nav-item">
        <a class="nav-link btn-primary active" aria-current="page" href="#">Forecast</a>
    </li>
    &nbsp;

    <li class="nav-item">
        <a class="nav-link btn-outline-info" href="history?name=<?= $response['location']['name'] ?>">History</a>
    </li>
    &nbsp;

    <li class="nav-item">
        <a class="nav-link btn-outline-dark" href="timeZone?name=<?= $response['location']['name'] ?>">Time Zone</a>
    </li>
    &nbsp;

    <li class="nav-item">
        <a class="nav-link btn-outline-info" href="sports?name=<?= $response['location']['name'] ?>">Sports</a>
    </li>
    &nbsp;

    <li class="nav-item">
        <a class="nav-link btn-outline-info" href="astronomy?name=<?= $response['location']['name'] ?>">Astronomy</a>
    </li>
    &nbsp;

    <li class="nav-item">
        <a class="nav-link btn-outline-danger" href="weatherAlerts?name=<?= $response['location']['name'] ?>">Weather Alerts</a>
    </li>
    &nbsp;

    <li class="nav-item">
        <a class="nav-link btn-outline-warning" href="airQuality?name=<?= $response['location']['name'] ?>">Air Quality</a>
    </li>
    &nbsp;

</ul>

<?php
$day = $response['forecast']['forecastday'][0]['hour'];
// echo "<pre>";
// // die;
// print_r($response['forecast']['forecastday'][0]['hour'][0]);

// die;
?>

<!-- < ?= $response ?> -->

<section class="vh-100">
    <div class="container py-5 h-100">
        
        <div class="row d-flex justify-content-center align-items-center h-100">
<!-- -------------------------------------------card division starts here ------------------------------- -->
<?php foreach($day as $time) { ?>
            <div class="col-md-8 col-lg-6 col-xl-4">
                <?php // print_r($time); ?>
                <?php // die; ?>

                <div class="card" style="color: #4B515D; border-radius: 35px; border-width: 5px">
                    <div class="card-body p-4">

                        <div class="d-flex">
                            <h6 class="flex-grow-1"><?= $response['location']['name'] ?></h6>
                            <h6><?= $time['time'] ?></h6>
                        </div>

                        <div class="d-flex flex-column text-center mt-5 mb-4">
                            <h6 class="display-4 mb-0 font-weight-bold" style="color: #1C2331;"> <?= $time['temp_c'] ?>°C / <?= $time['temp_f'] ?>°F  </h6>
                            <span class="medium" style="color: #868B94"><?= $time['condition']['text'] ?></span>
                        </div>
                        
                        <div class="d-flex align-items-center">
                            <div class="flex-grow-1" style="font-size: 1rem;">
                                <div><i class="fas fa-wind fa-fw" style="color: #868B94;"></i> <span class="ms-1">Wind Speed : <?= $time['wind_kph'] ?> km/h & <?= $time['wind_mph'] ?> m/h </span></div>
                                <div><i class="fas fa-tint fa-fw" style="color: #868B94;"></i> <span class="ms-1">Humidity : <?= $time['humidity'] ?> %</span></div>
                                <div><i class="fa-solid fa-clouds" style="color: #868B94;"></i> <span class="ms-1">Clouds : <?= $time['cloud'] ?> %</span></div>
                                <div><i class="fas fa-sun fa-fw" style="color: #868B94;"></i> <span class="ms-1">Wind Direction : <?= $time['wind_dir'] ?> </span></div>
                                <div><i class="fas fa-sun fa-fw" style="color: #868B94;"></i> <span class="ms-1">UV : <?= $time['uv'] ?> %</span></div>
                            </div>
                            <div>
                                <img src="<?= $time['condition']['icon'] ?>" width="100px">
                            </div>
                        </div>

                        
                    </div>
                    <!-- <span class="small text-center" style="color: #868B94">Last Updated : <?= $time['last_updated'] ?></span> -->
                </div>
                
            </div>
            
<?php } ?>
<!-- -------------------------------------------card division ends here ------------------------------- -->
        </div>

    </div>
</section>