<body class="bg-dark text-white">

<ul class="nav nav-pills nav-fill">
    <li class="nav-item">
        <a class="nav-link btn-outline-success" href="detailWeather?name=<?= $name ?>"><b>Current weather</b></a>
    </li>
    &nbsp;
    <li class="nav-item">
        <a class="nav-link btn-outline-primary" href="forecast?name=<?= $name ?>">Forecast</a>
    </li>
    &nbsp;

    <li class="nav-item">
        <a class="nav-link btn-info active" aria-current="page" href="#">History</a>
    </li>
    &nbsp;

    <li class="nav-item">
        <a class="nav-link btn-outline-light text-grey" href="timeZone?name=<?= $name ?>">Time Zone</a>
    </li>
    &nbsp;

    <li class="nav-item">
        <a class="nav-link btn-outline-info" href="sports?name=<?= $name ?>">Sports</a>
    </li>
    &nbsp;

    <li class="nav-item">
        <a class="nav-link btn-outline-info" href="astronomy?name=<?= $name ?>">Astronomy</a>
    </li>
    &nbsp;

    <li class="nav-item">
        <a class="nav-link btn-outline-danger" href="weatherAlerts?name=<?= $name ?>">Weather Alerts</a>
    </li>
    &nbsp;

    <li class="nav-item">
        <a class="nav-link btn-outline-warning" href="airQuality?name=<?= $name ?>">Air Quality</a>
    </li>
    &nbsp;

</ul>





<div class="container py-5">
    <div class="row">
        <div class="col-md-2 text-center">
            <p><i class="fa fa-exclamation-triangle fa-5x"></i><br />Status Code: 403</p>
        </div>
        <div class="col-md-10">
            <h3>OPPSSS!!!! Sorry...</h3>
            <p>API key is limited to get history data. Please check our pricing page and upgrade to higher plan.</p>
            <a class="btn btn-danger" href="forecast?name=<?= $name ?>">Go Back</a>
        </div>
    </div>
</div>

<div id="footer" class="text-center">
    <!-- Hak Cipta 2018, Garuda Cyber Technologies -->
</div>
</body>


<?php
