<!-- inside it! (WeatherApi) -->

<div class="container">
    <br />
    <h4 class="font-weight-light mb-4 font-italic"> Weather search bar </h4>
    <div class="row justify-content-center">
        <div class="col-12 col-md-10 col-lg-8">
            <form class="card card-sm" action="weatherApi/weatherGuzzle" method="post" >
                <div class="card-body row no-gutters align-items-center">
                    <div class="col-auto">
                        <i class="fas fa-search h4 text-body"> </i>
                    </div>
                    <div class="col">
                        <input class="form-control form-control-lg form-control-borderless" type="search" name="search" placeholder="Search location...">  
                    </div>  
                    <div class="col-auto" >
                        <button class="btn btn-lg btn-success" type="submit"> Search </button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
<form></form>