<?php

// echo "<pre>";
// echo "insicde|||";
// print_r($response);

foreach ($response as $key=>$locs)
{
    // print_r($locs);
    $name = $locs['name'];

    $name = strtolower($name);
        $sArr = explode(' ', $name);
        $urlFmt = implode('%20', $sArr);
    
?>
<div class="container mx-auto mt-4">
    <div class="row">
        <div class="col-md-4">
            <div class="card" style="width: 18rem;">
                <img src="https://png.pngtree.com/background/20211216/original/pngtree-photographs-of-tea-leaves-in-the-lush-tea-garden-on-the-picture-image_1538867.jpg" class="card-img-top" alt="...">
                <div class="card-body">
                    <label for="region"><h5 class="card-title"><?= $locs['name'] ?></h5>
                    <label for="region">Region : <b class="card-subtitle mb-2"><?= $locs['region'] ?></b></label><br>
                    <label for="region">Country : <b class="card-subtitle mb-2"><?= $locs['country'] ?></b></label><br>
                    <label for="region">Latitude : <b class="card-subtitle mb-2"><?= $locs['lat'] ?></b></label><br>
                    <label for="region">Longitude : <b class="card-subtitle mb-2"><?= $locs['lon'] ?></b></label><br>
                    <!-- <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                    <a href="#" class="btn mr-2"><i class="fas fa-link"></i> Visit Site</a> -->
                    <a href="detailWeather?name=<?= $locs['name'] ?>" class="btn ">view details</a>
                </div>
            </div>
        </div>
    </div>
</div>

<!--  -->
<?php }