<?php

// echo "<h1>Search for the weather of desired location!</h1>";

echo PHP_EOL;

// echo '<br>';

// echo $this->tag->linkTo(
//     'apiCheck',
//     'Check or Test for API!'
// );


echo '<br>';

echo $this->tag->linkTo(
    ['weatherApi',
    'Weather API',
    'class'=>"btn btn-lg btn-success"]
);

echo '<br>';
?>
<br><br>

<!-- <h3>Search for books from openlibrary.org</h3><br> -->

<?php // echo $this->tag->form("WeatherApi/weatherGuzzle"); ?>
    <p>
        <!-- <label for="search">Search : </label> -->
        <?php //echo $this->tag->textField("search"); ?>

    </p>

    <p>
        <?php //echo $this->tag->submitButton("Get locations"); ?>
    </p>
</form>