<?php


echo PHP_EOL;

?>
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Store</title>

</head>
<body>
    <h2>Click here to enter the store!</h2>

    <?php

    echo '<br>';

    echo $this->tag->linkTo(
        ['store',
        'Store App',
        'class'=>"btn btn-lg btn-success"]
    );

    echo '<br>';


    ?>


</body>

<script>
    
</script>

</html>
