<?php

// echo "<h1>Search for the weather of desired location!</h1>";

echo PHP_EOL;

// echo '<br>';

// echo $this->tag->linkTo(
//     'apiCheck',
//     'Check or Test for API!'
// );


// echo '<br>';

// echo $this->tag->linkTo(
//     ['spotify/authorization',
//     'Spotify App',
//     'class'=>"btn btn-lg btn-success"]
// );

// echo '<br>';
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Store</title>

</head>
<body>
    <h2>Click here to enter the store!</h2>

    <?php

    echo '<br>';

    echo $this->tag->linkTo(
        ['store',
        'Store App',
        'class'=>"btn btn-lg btn-success"]
    );

    echo '<br>';


    ?>


</body>

<script>
    
</script>

</html>
